#!/usr/bin/env python3
"""Rebuilds songs.js for the Album Board from the SBGLP writing-session folders.

Run from anywhere:  python3 build_songs.py
Default source: <this folder>/../../../../../SBGLP/02 Album Project/Writing Sessions
(the same relative layout on the Mac mini and on the PC's D:\\SYNCt).
Pass a different Writing Sessions path as the first argument to override.
"""
import json, os, re, sys, datetime
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "..", "SBGLP", "02 Album Project", "Writing Sessions"))
SESSIONS = {"2026-10-08-Reset": "Oct 8 Reset", "2026-10-09-Lyric-Mine": "Oct 9 Lyric Mine"}
STEM = re.compile(r"^(?P<slug>[a-z0-9-]+)_v(?P<ver>\d+)_(?P<writer>[A-Za-z]+)_lyrics\.md$")

def read(p):
    try:
        with open(p, encoding="utf-8") as f: return f.read()
    except OSError: return ""

songs = {}
for folder, label in SESSIONS.items():
    d = os.path.join(SRC, folder)
    if not os.path.isdir(d): continue
    for fn in sorted(os.listdir(d)):
        m = STEM.match(fn)
        if not m: continue
        stem = fn[:-len("_lyrics.md")]
        raw = read(os.path.join(d, fn))
        tm = re.match(r"# (.+)\n", raw)
        title = tm.group(1).strip() if tm else m["slug"].replace("-", " ").title()
        body = re.sub(r"\A# [^\n]*\n+", "", raw).strip("\n")
        sp = os.path.join(d, "Suno Pass")
        suno = {k: read(os.path.join(sp, f"{stem}_suno-{k}.txt")) for k in ("title", "lyrics", "style", "exclude")}
        if not suno["lyrics"]: suno["lyrics"] = body
        chars = len(suno["lyrics"].encode("utf-16-le")) // 2
        if suno["lyrics"].strip() == body.strip(): suno["lyrics"] = None  # same text; the page uses the lyrics field
        if not suno["title"]: suno["title"] = title
        header = re.search(r"^Version v\d+\..*$", read(os.path.join(d, stem + "_notes.md")), re.M)
        v = {"stem": stem, "version": int(m["ver"]), "writer": m["writer"], "session": label, "folder": folder,
             "title": title, "lyrics": body, "suno": suno, "header": header.group(0).replace("**", "") if header else "",
             "chars": chars}
        s = songs.setdefault(m["slug"], {"slug": m["slug"], "ep": m["slug"].startswith("ep"), "versions": []})
        s["versions"].append(v)

out = []
for slug, s in songs.items():
    s["versions"].sort(key=lambda v: (v["folder"], v["version"], v["writer"] == "Cue"))
    latest = s["versions"][-1]
    s.update(title=latest["title"], session=latest["session"], latest=latest["stem"])
    out.append(s)
out.sort(key=lambda s: (s["session"], s["title"].lower()))
built = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
js = "// Generated by build_songs.py. Do not edit by hand.\nwindow.ALBUM_BUILT = %s;\nwindow.ALBUM_SONGS = %s;\n" % (json.dumps(built), json.dumps(out, ensure_ascii=False))
with open(os.path.join(HERE, "songs.js"), "w", encoding="utf-8") as f: f.write(js)
print(f"{len(out)} songs, {sum(len(s['versions']) for s in out)} versions -> songs.js ({built})")
