const {chromium} = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const {execFileSync} = require('node:child_process');
const assert = require('node:assert/strict');
const ROOT = path.resolve(__dirname,'..');
const BASE = process.env.APP_BASE_URL;
const ARTIFACTS = process.env.ARTIFACT_DIR || path.join(ROOT,'..','album-board-verification');
function catalogue(text) { const ctx={window:{}}; vm.runInNewContext(text,ctx); return ctx.window; }
const current = catalogue(fs.readFileSync(path.join(ROOT,'album-board','songs.js'),'utf8'));
const original = catalogue(execFileSync('git',['show','HEAD:album-board/songs.js'],{cwd:ROOT,encoding:'utf8'}));
const oldVersions = original.ALBUM_SONGS.flatMap(s=>s.versions);
const allVersions = current.ALBUM_SONGS.flatMap(s=>s.versions);
assert.equal(new Set(allVersions.map(v=>v.stem)).size,allVersions.length,'Every version must have a distinct rating ID');
for(const old of oldVersions) assert(allVersions.some(v=>v.stem===old.stem && v.folder===old.folder),'Keep existing rating ID '+old.stem);
assert.equal(current.ALBUM_SESSIONS.reduce((n,s)=>n+s.versions,0),allVersions.length);
assert(allVersions.length>=oldVersions.length,'Existing versions must not disappear');
for(const folder of ['2026-10-04','2026-10-04-Cold-Pass','2026-10-08-Reset','2026-10-09-Lyric-Mine','2026-10-10-Cue-Battle01','2026-10-10-Misc-Battle01']) assert(current.ALBUM_SESSIONS.some(s=>s.folder===folder),'Missing session '+folder);
const checks = [];
function checked(label) { checks.push(label); console.log('PASS '+label); }
checked(`${allVersions.length} versions in ${current.ALBUM_SESSIONS.length} sessions; every old rating ID preserved`);
(async()=>{
  fs.mkdirSync(ARTIFACTS,{recursive:true});
  const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
  try {
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    await context.route('**/*',route=>new URL(route.request().url()).origin===new URL(BASE).origin ? route.continue() : route.abort());
    await context.addInitScript(()=>{
      window.__copied=null; window.__denyCopy=false;
      Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{if(window.__denyCopy)throw Error('test denial');window.__copied=text;}}});
      document.execCommand=()=>false;
    });
    const page=await context.newPage(), errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto(BASE+'/album-board/',{waitUntil:'networkidle'});
    const song = current.ALBUM_SONGS.find(s=>s.slug==='check-out');
    const old = song.versions[0];
    const seed={v:2,ratings:{[old.stem]:{score:87,note:'Existing note',status:'short'}},tracklist:['check-out'],pick:{'check-out':old.stem},custom:{'check-out':[{stem:'mine-existing',custom:true,label:'Existing edit',session:old.session,lyrics:'Existing edited lyric',suno:{title:'Edited title',style:'Edited style',exclude:'Edited exclude',lyrics:'Existing edited lyric'}}]}};
    seed.pick['missing-person']=original.ALBUM_SONGS.find(s=>s.slug==='missing-person').versions[0].stem;
    await page.evaluate(seed=>localStorage.setItem('grind.album.v1',JSON.stringify(seed)),seed);
    await page.reload({waitUntil:'networkidle'});
    await page.locator('.row[data-slug="check-out"]').click();
    assert.equal(await page.locator('#scoreNum').inputValue(),'87');
    assert.equal(await page.locator('#note').inputValue(),'Existing note');
    assert.equal(await page.locator('#detail [data-ver="mine-existing"]').count(),1);
    checked('Existing scores, notes, tracklist and editable versions survive catalogue expansion');
    for(const key of ['title','style','exclude','lyrics']) {
      const section=page.locator(`[data-field="${key}"]`), shown=await section.locator('pre').textContent();
      const expected=key==='lyrics'?(old.suno.lyrics ?? old.lyrics):old.suno[key];
      assert.equal(shown,expected,'Visible '+key+' matches exact copy text');
      await section.locator('[data-copy]').click();
      assert.equal(await page.evaluate(()=>window.__copied),expected,'Copy '+key+' uses visible text');
    }
    checked('Title, style, excluded styles and lyrics boxes copy exactly their displayed text');
    await page.locator('[data-copy="lyrics"]').scrollIntoViewIfNeeded();
    await page.evaluate(()=>window.__denyCopy=true);
    await page.locator('[data-copy="lyrics"]').click();
    assert.match(await page.locator('#toast').textContent(),/Copy failed/);
    await page.evaluate(()=>window.__denyCopy=false);
    checked('Clipboard denial does not report a successful copy');
    await page.locator('#copyEdit').click();
    await page.locator('#edStyle').fill('New edited style\nSecond line');
    await page.locator('[data-copy="style"]').click();
    assert.equal(await page.evaluate(()=>window.__copied),'New edited style\nSecond line');
    await page.reload({waitUntil:'networkidle'});
    await page.locator('.row[data-slug="check-out"]').click();
    assert.equal(await page.locator('#edStyle').inputValue(),'New edited style\nSecond line');
    checked('Edited fields copy immediately and persist after reload');
    await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new DOMException('test full','QuotaExceededError');};});
    await page.locator('#edStyle').fill('Still editable when storage is full');
    assert.match(await page.locator('#saveStatus').textContent(),/could not be saved/);
    await page.reload({waitUntil:'networkidle'});
    checked('Storage failures show an explicit export-before-closing warning');
    await page.getByRole('button',{name:'Oct 10 Cue Battle 01',exact:true}).click();
    assert.equal(await page.locator('#list .row').count(),7);
    await page.locator('.row[data-slug="missing-person"]').click();
    assert.match(await page.locator('#detail > .eyebrow').first().textContent(),/Oct 10 Cue/);
    assert.equal(await page.locator('[data-field="instrumental"]').count(),1);
    checked('Today’s Cue session selects seven songs and includes instrumental prompts');
    await page.getByRole('button',{name:'Oct 10 Misc Battle 01',exact:true}).click();
    assert.equal(await page.locator('#list .row').count(),7);
    await page.getByRole('button',{name:'Oct 4 Cold Pass',exact:true}).click();
    assert.equal(await page.locator('#list .row').count(),12);
    await page.locator('.row[data-slug="two-people-to-mourn"]').click();
    assert.match(await page.locator('#detail > .eyebrow').first().textContent(),/Oct 4/);
    assert.equal(await page.locator('[data-copy="style"]').isDisabled(),true);
    checked('Earlier sessions remain filterable even when a song has newer versions; missing prompts cannot copy blank text');
    await page.getByRole('button',{name:'All',exact:true}).click();
    await page.locator('#q').fill('Still editable when storage is full');
    assert.equal(await page.locator('#list .row').count(),0);
    await page.locator('#q').fill('Second line');
    assert.equal(await page.locator('#list .row').count(),1);
    await page.locator('#q').fill('');
    checked('Search finds saved custom prompts and excludes unsaved changes after reload');
    await page.locator('.row[data-slug="check-out"]').focus();
    await page.keyboard.press('Enter');
    assert.match(await page.locator('#detail h2').textContent(),/Check Out/);
    await page.locator('#detail [data-ver="'+old.stem+'"]').click();
    await page.screenshot({path:path.join(ARTIFACTS,'desktop.png'),fullPage:false});
    for(const width of [390,820,1440]) {
      await page.setViewportSize({width,height:900});
      const dimensions=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,width:document.documentElement.scrollWidth}));
      assert(dimensions.width<=dimensions.viewport+1,'Horizontal overflow at '+width);
    }
    await page.setViewportSize({width:390,height:844});
    await page.locator('[data-field="style"]').evaluate(el=>el.scrollIntoView({block:'start'}));
    await page.screenshot({path:path.join(ARTIFACTS,'phone.png'),fullPage:false});
    await page.locator('#detailBack').click();
    assert.equal(await page.locator('.row[data-slug="check-out"]').evaluate(el=>el===document.activeElement),true);
    checked('Keyboard selection and 390px, 820px and 1440px layouts work without horizontal overflow');
    await page.evaluate(async()=>{await navigator.serviceWorker.register('../service-worker.js');await navigator.serviceWorker.ready;});
    await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
    await context.setOffline(true);
    await page.reload({waitUntil:'domcontentloaded'});
    assert((await page.locator('#summary').textContent()).startsWith(`${current.ALBUM_SONGS.length} songs`));
    assert.equal(await page.getByRole('button',{name:'Oct 10 Misc Battle 01',exact:true}).count(),1);
    await context.setOffline(false);
    checked('Updated catalogue and session filters reload offline through the service worker');
    assert.deepEqual(errors,[],'No browser script errors');
    checked('No browser script errors; all non-local requests blocked');
    fs.writeFileSync(path.join(ARTIFACTS,'browser-results.json'),JSON.stringify({checks,errors},null,2));
    await context.close();
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
